[features]
seeds = false
[programs.localnet]
crowdfunding = "3yPnr14mxXLR8eFuQ6rqDbmbXEgogEtJWvtbLMEWwwV2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
